export enum MarketingsheetHeaders {
  Date = "Date",
  Name = "Name",
  PhoneNumber = "Phone",
  Email = "Email",
  Source = "SOURCE",
  Course = "Course",
  Area = "Area",
  City = "City",
  AssignedTo = "Assigned To",
  LeadType = "Lead Type",
  Remarks = "Remarks",
  AltPhoneNumber = "Alt Phone Number",
  Gender = "Gender",
  SchoolName = "School/College Name",
  Degree = "Degree",
}