export enum MarketingsheetHeaders {
  Date = 1,
  Name = 2,
  PhoneNumber = 3,
  Email = 4,
  Source = 5,
  Course = 6,
  Area = 7,
  City = 8,
  AssignedTo = 9,
  LeadType = 11,
  Remarks = 12,
  AltPhoneNumber = 13,
  Gender = 14,
  SchoolName = 15,
}
