export enum MarketingsheetHeaders {
  Date = 1,
  Name = 2,
  PhoneNumber = 3,
  Email = 4,
  Source = 5,
  Course = 8,
  Area = 9,
  City = 10,
  AssignedTo = 11,
  LeadType = 13,
  Remarks = 14,
  AltPhoneNumber = 15,
  Gender = 16,
  SchoolName = 17,
}
