 [
  'S. No.',
  'Course',
  'Form No.', //convert into formNo
  'Date of Admission',
  'Name of Student',
  "Father's Name",
  "Mother's Name",
  'Permanent Address',
  'District',
  'Pincode',
  'Date of Birth',
  'Contact / WhatsApp No. (Student)',
  'Contact No. (Parents)',
  'Email',
  'Gender',
  'Religion',
  'Category',
  'Blood Group',
  'Admitted Through',
  'College Name',
  'District',
  'Board / University',
  'Year of Passing',
  'Marks Obtained OR Percentage',
  '10th Marksheet',
  '10th Certificate',
  '12th Marksheet',
  '12th Certificate',
  'Graduation Final Year Marksheet',
  'Character',
  'T.C./Migration',
  'Medical Certificate',
  'Anti Ragging by Student',
  'Antiragging by Parent',
  'Allotment Letter',
  'Photo',
  'Caste',
  'Income',
  'Nivas',
  'Gap Affidavit',
  'Aadhaar',
  'Declaration Filled',
  'PYSICALLY HANDICAPPED',
  'EWS',
  'Ref',
  'Remarks'
]
export const sampleStudentData = {
  'S. No.': 1,
  Course: 'BVA (App Art)',
  'Form No.': 'TIHS2442',
  'Date of Admission': "2022-08-27T00:00:00.000Z",
  'Name of Student': 'AKANKSHA',
  "Father's Name": 'KULDEEP KUMAR DAS',
  "Mother's Name": 'REETA DEVI',
  'Permanent Address': 'VILL.&POST-SOHAWAL, TEHSIL- SOHAWAL ',
  District: 'BARABANKI',
  Pincode: 224188,
  'Date of Birth': "2004-09-11T00:00:00.000Z",
  'Contact / WhatsApp No. (Student)': 8604335002,
  'Contact No. (Parents)': 9451514456,
  Gender: 'FEMALE',
  Religion: 'HINDU',
  Category: 'SC',
  'Blood Group': 'AB+',
  'Admitted Through': 'DIRECT',
  'College Name': 'SAINIK PUBLIC SCHOOL',
  'Board / University': 'CBSE',
  'Year of Passing': 2022,
  'Marks Obtained OR Percentage': 69,
  '10th Marksheet': 'X',
  Character: 'Y',
  'T.C./Migration': 'Y',
  'Medical Certificate': 'Y',
  Photo: 'Y',
  Aadhaar: 'X',
  'Declaration Filled': 'Y'
}